from __future__ import annotations

STATUS_PENDING = "PENDING"
STATUS_PARTIAL = "PARTIAL"
STATUS_PAID = "PAID"
STATUS_OVERDUE = "OVERDUE"
STATUS_CANCELLED = "CANCELLED"
STATUS_DISPUTED = "DISPUTED"
STATUS_RESOLVED = "RESOLVED"
STATUS_REJECTED = "REJECTED"
STATUS_ARCHIVED = "ARCHIVED"

PAYMENT_ACTIVE_STATUSES = {STATUS_PENDING, STATUS_PARTIAL, STATUS_OVERDUE}
PAYMENT_CLOSED_STATUSES = {STATUS_PAID, STATUS_CANCELLED}
DISPUTE_OPEN_STATUSES = {"OPEN", "UNDER_REVIEW"}
